chrome_path = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
user_data_dir = "/Users/singhpra/Trading/ChromeDataDir"
chrome_args = []
launch_chrome_if_needed = true

log_config = "info,chromiumoxide=error,stock_themes=debug"

base_ticker = "SPY"
market_hours = ["06:30", "13:00"]

ignored_stocks = []

http_port = 8000
