CREATE TABLE IF NOT EXISTS tags
(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    name       TEXT     NOT NULL COLLATE NOCASE UNIQUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stock_tags
(
    ticker     TEXT     NOT NULL,
    tag_id     INTEGER  NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ticker, tag_id),
    FOREIGN KEY (tag_id) REFERENCES tags (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_stock_tags_tag_id ON stock_tags (tag_id);

INSERT OR IGNORE INTO tags (name)
VALUES ('Agriculture'),
       ('AgriTech'),
       ('AI Adopters'),
       ('AI Applications'),
       ('AI Infrastructure'),
       ('AI Software'),
       ('Autonomous Vehicles'),
       ('Biotechnology'),
       ('Blockchain'),
       ('Cloud Computing'),
       ('Cloud Security'),
       ('Cooling & Thermal Management'),
       ('Copper'),
       ('Critical Minerals'),
       ('Crypto Infrastructure'),
       ('Cybersecurity'),
       ('Data & Analytics'),
       ('Data Centers'),
       ('Defense & Aerospace'),
       ('Defense Technology'),
       ('Developer Tools'),
       ('Diagnostics'),
       ('Digital Advertising'),
       ('Digital Health'),
       ('Digital Infrastructure'),
       ('Digital Payments'),
       ('Drug Discovery'),
       ('Drones'),
       ('E-commerce'),
       ('Edge AI'),
       ('Electric Vehicles'),
       ('Electrical Equipment'),
       ('Energy Storage'),
       ('Enterprise Software'),
       ('Fintech'),
       ('Gaming'),
       ('Genomics'),
       ('GLP-1'),
       ('Identity Security'),
       ('Industrial Automation'),
       ('Insurtech'),
       ('Lab Automation'),
       ('Launch Vehicles'),
       ('LNG'),
       ('Logistics & Supply Chain'),
       ('Medical Devices'),
       ('Memory & Storage'),
       ('Natural Gas'),
       ('Networking Hardware'),
       ('Nuclear'),
       ('Obesity & Metabolic Health'),
       ('Oil & Gas'),
       ('Power Grid'),
       ('Power Infrastructure'),
       ('Quantum Computing'),
       ('REITs'),
       ('Renewable Energy'),
       ('Robotics'),
       ('Satellite Communications'),
       ('Satellite Imagery'),
       ('Semiconductors'),
       ('Social Media'),
       ('Solar'),
       ('Space Infrastructure'),
       ('Streaming'),
       ('Supply Chain Resilience'),
       ('Travel & Hospitality'),
       ('Uranium'),
       ('Utilities'),
       ('Water Infrastructure');
